name: Release Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2', '2.6']
        task: [lint, spec]
    steps:
      - name: ${{ matrix.ruby }} rake ${{ matrix.task }}
        steps:
        - uses: actions/checkout@v5
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: ${{ matrix.ruby }}
            bundler-cache: true # runs 'bundle install' and caches installed gems automatically

        - run: bundle exec rake ${{ matrix.task }}

      - name: Publish gem 
        if: success()
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: bundle exec rake release
