name: Release Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - name: Run rake lint
        run: bundle exec rake lint        

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2', '2.7']
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          # Prevent Bundler version to be read from Gemfile.lock to prevent setup-ruby
          # from trying to install a Bundler version incompatible with older Ruby versions
          bundler: default
      - name: Run rake spec
        run: bundle exec rake spec

  release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Ruby and bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - name: Publish gem 
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: bundle exec rake release